.\" Manual page for internsctl
.TH INTERNSCTL 1 " 19 December 2023" "v0.1.0" "Internsctl Manual"
.SH NAME
internsctl \- Custom Linux command

.SH SYNOPSIS
.B internsctl
[\fIoptions\fR] {\fIcpu|memory|user|file\fR} {\fIsub-command\fR} [\fIarguments\fR]

.SH DESCRIPTION
.PP
The \fBinternsctl\fR command is a custom Linux command that provides various sub-commands for system-related operations.

.SH OPTIONS
.PP
\fB--help\fR
.TP
\fB--version\fR
Display version information.

.SH SEE ALSO
.PP
For detailed documentation, refer to the manual page by running:
.BR man internsctl

.SH AUTHOR
.PP
Written by Rishabh Mishra.

.SH BUGS
.PP
No known bugs.

.SH VERSION
.PP
v0.1.0

.SH REPORTING BUGS
.PP
Report bugs to: rishabhmishra8118@gmail.com
